In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression , Ridge , Lasso
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv("06_car-mpg.csv")

In [3]:
df.head()

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64
 2   disp      398 non-null    float64
 3   hp        398 non-null    str
 4   wt        398 non-null    int64
 5   acc       398 non-null    float64
 6   yr        398 non-null    int64
 7   origin    398 non-null    int64
 8   car_type  398 non-null    int64
 9   car_name  398 non-null    str
dtypes: float64(3), int64(5), str(2)
memory usage: 38.4 KB

In [5]:
df.isnull().sum()

mpg         0
cyl         0
disp        0
hp          0
wt          0
acc         0
yr          0
origin      0
car_type    0
car_name    0
dtype: int64

In [6]:
df.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'wt', 'acc', 'yr', 'origin', 'car_type',
       'car_name'],
      dtype='str')

In [7]:
df.head(1)

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu

In [8]:
df = df.drop(['car_name'],axis=1)
df['origin'] = df['origin'].replace({1:'america',2:'europe',3:'asia'})
df = pd.get_dummies(df , columns=['origin'], dtype=int)

In [10]:

df = df.replace('?',np.nan)
df = df.apply(pd.to_numeric)

df = df.apply(lambda x:x.fillna(x.median()) if x.dtype != 'object' else x , axis=0)

In [11]:
x = df.drop(['mpg'], axis = 1)
y = df[['mpg']]

In [12]:
x_s = preprocessing.scale(x)

In [13]:
y_s = preprocessing.scale(y)
y_s

array([[-7.06438701e-01],
       [-1.09075062e+00],
       [-7.06438701e-01],
       [-9.62646649e-01],
       [-8.34542675e-01],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.09075062e+00],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [ 6.21851453e-02],
       [-1.94022803e-01],
       [-7.06438701e-01],
       [-3.22126778e-01],
       [ 4.46497068e-01],
       [ 3.18393094e-01],
       [ 1.90289120e-01],
       [ 6.21851453e-02],
       [ 1.90289120e-01],
       [ 3.18393094e-01],
       [-3.22126778e-01],
       [-1.73127050e+00],
       [-1.73127050e+00],
       [-1.60316652e+00],
       [-1.85937447e+00],
       [ 4.46497068e-01],
       [ 5.74601043e-01],
       [ 1.90289120e-01],
       [ 1.90289120e-01],
       [-5.78334726e-01],
       [-9.62646649e-01],
       [-8.34542675e-01],
       [-5.78334726e-01],
       [-7.06438701e-01],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.47506255e+00],
       [-1.34695857e+00],
       [-1.34695857e+00],
       [-7.06438701e-01],
       [-1.94022803e-01],
       [-5.78334726e-01],
       [-7.06438701e-01],
       [-6.59188290e-02],
       [ 5.74601043e-01],
       [ 8.30808991e-01],
       [ 8.30808991e-01],
       [ 9.58912966e-01],
       [ 1.47132886e+00],
       [ 4.46497068e-01],
       [ 3.18393094e-01],
       [ 6.21851453e-02],
       [ 1.90289120e-01],
       [-6.59188290e-02],
       [-4.50230752e-01],
       [-3.22126778e-01],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-1.09075062e+00],
       [-1.21885460e+00],
       [-8.34542675e-01],
       [-1.60316652e+00],
       [-1.34695857e+00],
       [-1.47506255e+00],
       [-1.34695857e+00],
       [-5.78334726e-01],
       [-1.09075062e+00],
       [-1.34695857e+00],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-7.06438701e-01],
       [-1.94022803e-01],
       [-3.22126778e-01],
       [ 3.18393094e-01],
       [-1.94022803e-01],
       [ 5.74601043e-01],
       [-6.59188290e-02],
       [ 5.74601043e-01],
       [ 4.46497068e-01],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-1.09075062e+00],
       [-1.47506255e+00],
       [-1.34695857e+00],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-1.34695857e+00],
       [-1.47506255e+00],
       [-1.34695857e+00],
       [-7.06438701e-01],
       [-9.62646649e-01],
       [-7.06438701e-01],
       [-7.06438701e-01],
       [-6.59188290e-02],
       [ 3.18393094e-01],
       [-1.60316652e+00],
       [-1.47506255e+00],
       [-1.34695857e+00],
       [-1.47506255e+00],
       [-7.06438701e-01],
       [-4.50230752e-01],
       [-3.22126778e-01],
       [-1.94022803e-01],
       [-7.06438701e-01],
       [-5.78334726e-01],
       [-3.22126778e-01],
       [ 3.18393094e-01],
       [-1.09075062e+00],
       [-9.62646649e-01],
       [ 7.02705017e-01],
       [ 6.21851453e-02],
       [-4.50230752e-01],
       [-5.78334726e-01],
       [-1.09075062e+00],
       [ 6.21851453e-02],
       [-4.50230752e-01],
       [-1.60316652e+00],
       [-4.50230752e-01],
       [-3.22126778e-01],
       [-5.78334726e-01],
       [-1.09075062e+00],
       [ 9.58912966e-01],
       [ 3.18393094e-01],
       [ 1.08701694e+00],
       [ 1.90289120e-01],
       [-9.62646649e-01],
       [-9.62646649e-01],
       [-7.06438701e-01],
       [-9.62646649e-01],
       [-1.34695857e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [-1.21885460e+00],
       [ 7.02705017e-01],
       [ 3.18393094e-01],
       [ 3.18393094e-01],
       [ 9.58912966e-01],
       [ 1.08701694e+00],
       [ 5.74601043e-01],
       [ 6.21851453e-02],
       [ 3.18393094e-01],
       [ 6.21851453e-02],
       [ 3.18393094e-01],
       [ 9.58912966e-01],
       [-5.78334726e-01],
       [-7.06438701e-01],
       [-1.09075062e+00],
       [-1.09075062e+00],
       [-9.62646649e-01],
       [-1.09075062e+00],
       [-9.62646649e-01],
       [-1.21885460e+00],
       [-8.34542675e-01],
       [-9.62646649e-01],
       [-1.09075062e+00],
       [-7.06438701e-01],
       [-3.22126778e-01],
       [-4.50230752e-01],
       [-1.34695857e+00],
       [ 7.02705017e-01],
       [-6.59188290e-02],
       [-4.50230752e-01],
       [-6.59188290e-02],
       [ 6.21851453e-02],
       [ 1.90289120e-01],
       [ 6.21851453e-02],
       [-7.06438701e-01],
       [ 7.02705017e-01],
       [-5.78334726e-01],
       [-6.59188290e-02],
       [-6.59188290e-02],
       [-1.94022803e-01],
       [ 1.90289120e-01],
       [ 1.21512091e+00],
       [ 5.74601043e-01],
       [ 1.90289120e-01],
       [ 1.90289120e-01],
       [ 3.18393094e-01],
       [ 4.46497068e-01],
       [-7.70490688e-01],
       [-9.62646649e-01],
       [-1.02669864e+00],
       [-1.15480261e+00],
       [-1.94022803e-01],
       [-1.94022803e-01],
       [ 6.21851453e-02],
       [-1.29970816e-01],
       [ 7.02705017e-01],
       [ 1.26237132e-01],
       [ 7.02705017e-01],
       [ 1.21512091e+00],
       [-4.50230752e-01],
       [-7.06438701e-01],
       [-6.42386713e-01],
       [-7.70490688e-01],
       [ 7.66757004e-01],
       [ 1.08701694e+00],
       [ 5.74601043e-01],
       [ 3.82445081e-01],
       [-4.50230752e-01],
       [-1.34695857e+00],
       [-5.78334726e-01],
       [-5.78334726e-01],
       [-8.98594662e-01],
       [-8.98594662e-01],
       [-1.34695857e+00],
       [-1.34695857e+00],
       [-1.34695857e+00],
       [ 1.02296495e+00],
       [ 8.30808991e-01],
       [ 1.59943284e+00],
       [ 2.54341107e-01],
       [ 1.27917290e+00],
       [-7.70490688e-01],
       [-8.34542675e-01],
       [-1.02669864e+00],
       [-1.09075062e+00],
       [-7.70490688e-01],
       [-3.86178765e-01],
       [-5.78334726e-01],
       [-6.42386713e-01],
       [-9.62646649e-01],
       [-1.02669864e+00],
       [-1.02669864e+00],
       [-9.62646649e-01],
       [ 7.02705017e-01],
       [ 1.26237132e-01],
       [ 3.18393094e-01],
       [ 2.54341107e-01],
       [ 8.94860978e-01],
       [ 1.27917290e+00],
       [ 8.30808991e-01],
       [ 8.94860978e-01],
       [-1.94022803e-01],
       [-2.58074790e-01],
       [-2.58074790e-01],
       [ 2.50897106e+00],
       [ 1.61224323e+00],
       [ 1.18950012e+00],
       [ 2.03498635e+00],
       [ 1.61224323e+00],
       [-4.63041149e-01],
       [-5.27093137e-01],
       [-4.24609957e-01],
       [-5.52713931e-01],
       [-3.86178765e-01],
       [-4.24609957e-01],
       [ 2.03099517e-01],
       [-3.86178765e-01],
       [-5.27093137e-01],
       [-3.73368367e-01],
       [-3.47747573e-01],
       [-6.29576316e-01],
       [-6.93628303e-01],
       [-5.52713931e-01],
       [-7.44869893e-01],
       [-6.93628303e-01],
       [-7.70490688e-01],
       [ 8.30808991e-01],
       [ 5.10549055e-01],
       [ 4.72117863e-01],
       [ 9.46102568e-01],
       [-3.09316380e-01],
       [-4.02980341e-02],
       [ 3.65643505e-02],
       [ 4.93747479e-02],
       [-4.11799560e-01],
       [-8.34542675e-01],
       [-2.45264393e-01],
       [-9.37025854e-01],
       [ 1.02296495e+00],
       [ 7.66757004e-01],
       [-2.58074790e-01],
       [-4.75851547e-01],
       [-1.55591611e-01],
       [-4.24609957e-01],
       [-3.73368367e-01],
       [-8.34542675e-01],
       [-7.57680290e-01],
       [-8.98594662e-01],
       [-6.80817906e-01],
       [-8.47353072e-01],
       [-1.02669864e+00],
       [-5.52713931e-01],
       [-6.42386713e-01],
       [ 1.07420654e+00],
       [ 1.35603529e+00],
       [ 1.56100164e+00],
       [ 4.97738658e-01],
       [ 2.41530709e-01],
       [-6.59188290e-02],
       [ 4.72117863e-01],
       [ 4.93747479e-02],
       [ 1.36884568e+00],
       [ 1.40727688e+00],
       [ 1.06139615e+00],
       [ 1.76596800e+00],
       [ 6.25842632e-01],
       [ 6.77084222e-01],
       [ 4.20876273e-01],
       [ 1.27917290e+00],
       [ 2.30400470e+00],
       [ 1.86845118e+00],
       [ 1.09982734e+00],
       [ 1.75315761e+00],
       [ 5.74601043e-01],
       [ 3.69634684e-01],
       [ 1.00616338e-01],
       [-5.65524329e-01],
       [ 1.38165608e+00],
       [ 8.05188196e-01],
       [ 9.97344158e-01],
       [ 1.72753681e+00],
       [ 1.11263773e+00],
       [ 2.95733497e+00],
       [ 5.61790645e-01],
       [ 2.21433191e+00],
       [ 2.66269582e+00],
       [ 2.54740225e+00],
       [ 1.65067443e+00],
       [ 8.30808991e-01],
       [ 2.70112702e+00],
       [ 2.22714231e+00],
       [ 1.31760409e+00],
       [ 8.05188196e-01],
       [ 1.17668972e+00],
       [ 2.37539530e-02],
       [ 1.47132886e+00],
       [ 1.09435556e-02],
       [ 1.13825853e+00],
       [ 4.72117863e-01],
       [ 3.95255479e-01],
       [ 2.92772299e-01],
       [-1.86684184e-03],
       [ 8.30808991e-01],
       [ 1.99655516e+00],
       [ 1.98374476e+00],
       [ 1.48413926e+00],
       [ 1.12544813e+00],
       [ 1.72753681e+00],
       [ 1.81720959e+00],
       [ 1.35603529e+00],
       [ 1.43289767e+00],
       [ 1.39446648e+00],
       [ 8.17998594e-01],
       [ 1.21512091e+00],
       [ 1.40727688e+00],
       [ 1.30479370e+00],
       [ 1.13825853e+00],
       [ 1.20231052e+00],
       [ 1.03577535e+00],
       [ 5.87411440e-01],
       [ 9.20481773e-01],
       [ 2.41530709e-01],
       [ 8.78059402e-02],
       [-1.42781214e-01],
       [ 3.95255479e-01],
       [-4.24609957e-01],
       [-7.57680290e-01],
       [ 5.74601043e-01],
       [ 4.46497068e-01],
       [ 1.34322489e+00],
       [ 9.58912966e-01],
       [ 7.02705017e-01],
       [ 4.46497068e-01],
       [ 6.21851453e-02],
       [-6.59188290e-02],
       [ 1.59943284e+00],
       [ 1.72753681e+00],
       [ 9.58912966e-01],
       [ 1.85564079e+00],
       [ 1.59943284e+00],
       [ 1.59943284e+00],
       [ 1.59943284e+00],
       [ 1.34322489e+00],
       [ 1.85564079e+00],
       [ 1.08701694e+00],
       [ 1.85564079e+00],
       [ 1.90289120e-01],
       [ 1.85564079e+00],
       [ 3.18393094e-01],
       [-1.94022803e-01],
       [ 1.08701694e+00],
       [ 1.59943284e+00],
       [ 4.46497068e-01],
       [ 4.46497068e-01],
       [ 2.62426463e+00],
       [ 1.08701694e+00],
       [ 5.74601043e-01],
       [ 9.58912966e-01]])

In [14]:
x_s = pd.DataFrame(x_s, columns=x.columns)
y_s = pd.DataFrame(y_s, columns=y.columns)

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x_s, y_s, test_size=0.3, random_state=0)

In [16]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(x_test.shape)

(278, 10)
(120, 10)
(278, 1)
(120, 10)

In [17]:
regression_model = LinearRegression()
regression_model.fit(x_train, y_train)

for idx, col_name in enumerate(x_train.columns):
    print('The coef for {} is {}'.format(col_name, regression_model.coef_[0][idx]))
    
print('======')

intercept = regression_model.intercept_[0]
print('The intercept is {}'.format(intercept))

print('======')

The coef for cyl is 0.2474447975894671
The coef for disp is 0.28838215446098686
The coef for hp is -0.18990342687152878
The coef for wt is -0.673222906511177
The coef for acc is 0.0675450154068818
The coef for yr is 0.34463640721172734
The coef for car_type is 0.31491491540037686
The coef for origin_america is -0.07682943694882902
The coef for origin_asia is 0.0633604889661997
The coef for origin_europe is 0.031283357351475284
======
The intercept is -0.019500467624017432
======

# RIDGE MODEL

In [19]:
ridge_model = Ridge(alpha=0.3)
ridge_model.fit(x_train,y_train)

print('Ridge model coef: {}'.format(ridge_model.coef_))

Ridge model coef: [ 0.24424435  0.27853222 -0.18980689 -0.66458446  0.06588077  0.34396213
  0.31169746 -0.07642734  0.06333336  0.03080065]

# lasso model

In [18]:
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(x_train,y_train)

print('Lasso model coef: {}'.format(lasso_model.coef_))

Lasso model coef: [-0.         -0.         -0.06203044 -0.48363379  0.          0.27163751
  0.09620861 -0.03490256  0.          0.        ]

In [20]:
print(regression_model.score(x_train, y_train))
print(regression_model.score(x_test, y_test))
print('***')
print(ridge_model.score(x_train,y_train))
print(ridge_model.score(x_test,y_test))
print('***')
print(lasso_model.score(x_train,y_train))
print(lasso_model.score(x_test,y_test))

0.836163800114943
0.8439452810748138
***
0.8361520170844985
0.8437853815947187
***
0.7994535676270829
0.81026554865651